### ISSUE TITLE
Prepare Hyperdrive Website for Testnet

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-website#3]
- [x] Add brand page - Logo lockups, primary brand colors, logo mark
- [x] FAQs
- [x] Add link to the app
    - [x] Blocked by launch of the app (@DannyDelott @jackburrus)
    - [x] Make a decision on the URL (cc. @jrhea) -- the URL is `.trading` (@jrhea to do a full domain forward to `.box` in the near future)
        - [x] Worst Case: `/testnet` or `/app`
- [x] Add link to BA (we'll put coming soon until the link is available)
    - [x] Blocked by their launch (@akhamisa)
- [x] Add link to the whitepaper
    - [x] Blocked by launch of whitepaper (@jrhea)

**Comment by akhamisa** [comment]
website FAQs here (vetted & approved by legal):
https://docs.google.com/document/d/1R72Zz31UgNyL6Q_HyxS72P_ttlWeck9yxXifMVlPM04/edit?usp=sharing

BA dashboard won't go live until the second week of testnet; we'll be QAing during the first week.
